project:
  type: website
  output-dir: docs

website:
  title: "Bash Live Demo"
  repo-url: https://github.com/jmc108/quarto-bash-demo
  repo-actions: [source]

engine: jupyter

format:
  html:
    code-tools: true
    thebe:
      use-binder: true
      binder:
        url: https://mybinder.org
        repo: jmc108/quarto-bash-demo
        branch: main
      kernelName: bash

execute:
  eval: false
