project:
  type: website
  output-dir: docs

website:
  title: "Bash Live Demo"

engine: jupyter

format:
  html:
    code-tools: true
    include-in-header: thebe-setup.html
    include-after-body: thebe-init.html

execute:
  eval: false
