project:
  type: website
  output-dir: docs

website:
  title: "Bash Live Demo"

engine: jupyter

format:
  html:
    code-tools: true
    thebe:
      use-binder: true
      binder:
        url: https://mybinder.org
        repo: jmc108/quarto-bash-demo
        branch: main
      kernelName: bash

execute:
  eval: false
